require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Customer = require('../models/Customer');
const Sequence = require('../models/Sequence');

const sampleCustomers = [
  {
    customerId: 'CUS-000001',
    formVersion: 1,
    data: {
      customerId: 'CUS-000001',
      entryDate: '2026-08-01',
      customerName: 'Sivaraman & Co (Siva Builders)',
      phone: '9876543210',
      location: 'Madurai Bypass Road',
      leadSource: 'Walk-in',
      salesperson: 'Karthik Raja',
      customerType: 'Building Owner',
      houseStage: 'Plastering',
      requirement: ['Tiles', 'Sanitary', 'Adhesive'],
      approxQuantity: '2500 Sq.Ft',
      tileBudget: 245000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 245000,
      quotationDate: '2026-08-02',
      status: 'Quotation',
      nextFollowUp: '2026-08-20',
      lastFollowUp: '2026-08-15',
      followUpCount: 2,
      orderValue: 0,
      lastReason: 'Reviewing tile catalogue for living room and master bath',
      crossSell: ['Grout & Epoxy', 'Tile Spacers & Levellers'],
    },
    createdBy: { name: 'Karthik Raja', role: 'owner' },
  },
  {
    customerId: 'CUS-000002',
    formVersion: 1,
    data: {
      customerId: 'CUS-000002',
      entryDate: '2026-08-03',
      customerName: 'Er. Murugesan (Sri Sai Builders)',
      phone: '9841234567',
      location: 'KK Nagar, Madurai',
      leadSource: 'Engineer',
      salesperson: 'Senthil Kumar',
      customerType: 'Architect',
      houseStage: 'Brickwork',
      requirement: ['Tiles', 'Sanitary', 'Clipping'],
      approxQuantity: '5000 Sq.Ft',
      tileBudget: 510000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 510000,
      quotationDate: '2026-08-05',
      status: 'Negotiation',
      nextFollowUp: '2026-08-19',
      lastFollowUp: '2026-08-14',
      followUpCount: 3,
      orderValue: 0,
      lastReason: 'Bulk commercial rate discount discussion in progress',
      crossSell: ['Waterproofing Chemicals', 'Bath Fittings & Faucets'],
    },
    createdBy: { name: 'Senthil Kumar', role: 'employee' },
  },
  {
    customerId: 'CUS-000003',
    formVersion: 1,
    data: {
      customerId: 'CUS-000003',
      entryDate: '2026-08-05',
      customerName: 'M. Jayaprakash (Mason Head)',
      phone: '9444112233',
      location: 'Melur Town',
      leadSource: 'Contractor',
      salesperson: 'Karthik Raja',
      customerType: 'Mason',
      houseStage: 'Painting',
      requirement: ['Adhesive', 'Clipping'],
      approxQuantity: '1200 Sq.Ft',
      tileBudget: 88000,
      sanitaryRequirement: 'No',
      adhesiveRequirement: 'Yes',
      quotationValue: 88000,
      quotationDate: '2026-08-06',
      status: 'Order Confirmed',
      nextFollowUp: '2026-08-25',
      lastFollowUp: '2026-08-16',
      followUpCount: 1,
      orderValue: 88000,
      lastReason: 'Order booked and dispatch scheduled for Friday',
      crossSell: ['Tile Spacers & Levellers'],
    },
    createdBy: { name: 'Karthik Raja', role: 'owner' },
  },
  {
    customerId: 'CUS-000004',
    formVersion: 1,
    data: {
      customerId: 'CUS-000004',
      entryDate: '2026-08-08',
      customerName: 'Dr. Anitha Meenakshi',
      phone: '9840556677',
      location: 'Anna Nagar West',
      leadSource: 'Referral',
      salesperson: 'Priya Dharshini',
      customerType: 'Building Owner',
      houseStage: 'Foundation',
      requirement: ['Tiles', 'Sanitary'],
      approxQuantity: '3200 Sq.Ft',
      tileBudget: 250000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 250000,
      quotationDate: '2026-08-10',
      status: 'Newly Contacted',
      nextFollowUp: '2026-08-22',
      lastFollowUp: '2026-08-12',
      followUpCount: 1,
      orderValue: 0,
      lastReason: 'Initial showroom visit and design consultation completed',
      crossSell: ['Bath Fittings & Faucets', 'Mirror Cabinets & Vanity'],
    },
    createdBy: { name: 'Priya Dharshini', role: 'employee' },
  },
  {
    customerId: 'CUS-000005',
    formVersion: 1,
    data: {
      customerId: 'CUS-000005',
      entryDate: '2026-08-11',
      customerName: 'Mobile Realtime Test Customer',
      phone: '9842112233',
      location: 'Showroom Live Entry',
      leadSource: 'Walk-in',
      salesperson: 'Karthik Raja',
      customerType: 'Building Owner',
      houseStage: 'Plastering',
      requirement: ['Tiles', 'Sanitary', 'Adhesive'],
      approxQuantity: '4000 Sq.Ft',
      tileBudget: 420000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 420000,
      quotationDate: '2026-08-12',
      status: 'Quotation',
      nextFollowUp: '2026-08-25',
      lastFollowUp: '2026-08-16',
      followUpCount: 2,
      orderValue: 0,
      lastReason: 'Live quotation generated during walk-in demonstration',
      crossSell: ['Grout & Epoxy', 'Kitchen Sinks'],
    },
    createdBy: { name: 'Karthik Raja', role: 'owner' },
  },
  {
    customerId: 'CUS-000006',
    formVersion: 1,
    data: {
      customerId: 'CUS-000006',
      entryDate: '2026-08-12',
      customerName: 'Vasanth Kumar (Greenfield Villa)',
      phone: '9840123987',
      location: 'TVS Nagar, Madurai',
      leadSource: 'Builder',
      salesperson: 'Priya Dharshini',
      customerType: 'Building Owner',
      houseStage: 'Building Completion',
      requirement: ['Tiles', 'Sanitary', 'Adhesive', 'Clipping'],
      approxQuantity: '6500 Sq.Ft',
      tileBudget: 680000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 680000,
      quotationDate: '2026-08-13',
      status: 'Order Confirmed',
      nextFollowUp: '2026-08-28',
      lastFollowUp: '2026-08-16',
      followUpCount: 4,
      orderValue: 680000,
      lastReason: 'Final payment received; delivery scheduled',
      crossSell: ['Grout & Epoxy', 'Waterproofing Chemicals', 'Bath Fittings & Faucets'],
    },
    createdBy: { name: 'Priya Dharshini', role: 'employee' },
  },
  {
    customerId: 'CUS-000007',
    formVersion: 1,
    data: {
      customerId: 'CUS-000007',
      entryDate: '2026-08-13',
      customerName: 'Rajesh & Associates (Architects)',
      phone: '9789012345',
      location: 'Mattuthavani',
      leadSource: 'Architect',
      salesperson: 'Senthil Kumar',
      customerType: 'Architect',
      houseStage: 'Brickwork',
      requirement: ['Tiles', 'Sanitary'],
      approxQuantity: '8000 Sq.Ft',
      tileBudget: 850000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 850000,
      quotationDate: '2026-08-14',
      status: 'Follow-up',
      nextFollowUp: '2026-08-24',
      lastFollowUp: '2026-08-17',
      followUpCount: 2,
      orderValue: 0,
      lastReason: 'Awaiting client approval for vitrified tile sample mockups',
      crossSell: ['Kitchen Sinks', 'Mirror Cabinets & Vanity'],
    },
    createdBy: { name: 'Senthil Kumar', role: 'employee' },
  },
  {
    customerId: 'CUS-000008',
    formVersion: 1,
    data: {
      customerId: 'CUS-000008',
      entryDate: '2026-08-14',
      customerName: 'Kannan Mason Works',
      phone: '9843210987',
      location: 'Othakadai',
      leadSource: 'Contractor',
      salesperson: 'Karthik Raja',
      customerType: 'Mason',
      houseStage: 'Plastering',
      requirement: ['Adhesive', 'Clipping'],
      approxQuantity: '1800 Sq.Ft',
      tileBudget: 120000,
      sanitaryRequirement: 'No',
      adhesiveRequirement: 'Yes',
      quotationValue: 120000,
      quotationDate: '2026-08-15',
      status: 'Walk-in',
      nextFollowUp: '2026-08-26',
      lastFollowUp: '2026-08-16',
      followUpCount: 1,
      orderValue: 0,
      lastReason: 'Sample adhesive bags given for test application',
      crossSell: ['Tile Spacers & Levellers'],
    },
    createdBy: { name: 'Karthik Raja', role: 'owner' },
  },
  {
    customerId: 'CUS-000009',
    formVersion: 1,
    data: {
      customerId: 'CUS-000009',
      entryDate: '2026-08-15',
      customerName: 'Kavitha Sundaram',
      phone: '9443219876',
      location: 'Gomathipuram',
      leadSource: 'Existing Customer',
      salesperson: 'Priya Dharshini',
      customerType: 'Building Owner',
      houseStage: 'Foundation',
      requirement: ['Tiles', 'Sanitary'],
      approxQuantity: '4500 Sq.Ft',
      tileBudget: 375000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 375000,
      quotationDate: '2026-08-16',
      status: 'Future Requirement',
      nextFollowUp: '2026-08-30',
      lastFollowUp: '2026-08-16',
      followUpCount: 1,
      orderValue: 0,
      lastReason: 'House construction at basement level; follow-up late August',
      crossSell: ['Bath Fittings & Faucets'],
    },
    createdBy: { name: 'Priya Dharshini', role: 'employee' },
  },
  {
    customerId: 'CUS-000010',
    formVersion: 1,
    data: {
      customerId: 'CUS-000010',
      entryDate: '2026-08-16',
      customerName: 'Meenakshi Hospital Extension',
      phone: '9894012345',
      location: 'East Veli Street',
      leadSource: 'Builder',
      salesperson: 'Karthik Raja',
      customerType: 'Building Owner',
      houseStage: 'Painting',
      requirement: ['Tiles', 'Sanitary', 'Adhesive'],
      approxQuantity: '12000 Sq.Ft',
      tileBudget: 1200000,
      sanitaryRequirement: 'Yes',
      adhesiveRequirement: 'Yes',
      quotationValue: 1200000,
      quotationDate: '2026-08-17',
      status: 'Negotiation',
      nextFollowUp: '2026-08-21',
      lastFollowUp: '2026-08-17',
      followUpCount: 3,
      orderValue: 0,
      lastReason: 'Hospitality & anti-skid antibacterial tiles presentation',
      crossSell: ['Grout & Epoxy', 'Waterproofing Chemicals'],
    },
    createdBy: { name: 'Karthik Raja', role: 'owner' },
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI;
  if (!uri) {
    console.error('MONGODB_URI missing in .env');
    process.exit(1);
  }

  await mongoose.connect(uri);
  console.log('Connected to MongoDB Atlas');

  // Clear existing and seed sample records
  await Customer.deleteMany({});
  console.log('Cleared existing customer records');

  for (const item of sampleCustomers) {
    const doc = new Customer(item);
    await doc.save();
    console.log(`Saved: ${item.customerId} - ${item.data.customerName}`);
  }

  // Update Sequence to 10
  await Sequence.findOneAndUpdate(
    { key: 'customer' },
    { $set: { currentValue: 10, prefix: 'CUS-', padding: 6 } },
    { upsert: true }
  );
  console.log('Updated ID sequence currentValue to 10');

  console.log('Seed completed successfully! 10 customer records inserted.');
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('Seed error:', err);
  process.exit(1);
});
